#!/usr/bin/env zsh

################################################################################
# Download a series of audio files from a youtube playlist in opus format.
# ------------------------------------------------------------------------
# Args:
#     1. File name
#     2. url
#
# Exports:
#     REPLY
################################################################################

emulate -L zsh

setopt pipefail

local function _dl_yt_video_max() {
    if ! (( ${+commands[yt-dlp]} )); then
        REPLY="ERROR: yt-dlp is required."
        return 1
    fi

    if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
        local help="Download video in best available quality (audio + video).\n\n"
        help+="Args:\n"
        help+="  1. File name\n"
        help+="  2. url"

        print -- "$help"
        return 0
    fi

    if (( $# != 2 )); then
        REPLY="ERROR: Two args expected. \n\nPass '--help' or '-h' to show help page."
        return 1
    fi

    local title="$1"
    local url="$2"

    yt-dlp \
        -S "vcodec:av01,vcodec:vp9" \
        -f "bv*+ba/b" \
        --merge-output-format mkv \
        -o "${title}.%(ext)s" \
        "$url" || {
            REPLY="ERROR: yt-dlp failed"
            return 1
        }
}

_dl_yt_video_max "$@" || print -- "$REPLY"
