#!/usr/bin/env zsh

################################################################################
# Download a series of audio files from a youtube playlist in opus format.
# ------------------------------------------------------------------------
# Args:
#     1. Generic title
#     2. url
#
# Exports:
#     REPLY
################################################################################

emulate -L zsh

setopt pipefail

local help_page
help_page+="Download a full yt playlists audio in .opus format.\n"
help_page+="\n"
help_page+="Args:\n"
help_page+="  1. Generic title\n"
help_page+="  2. url"

local function _dl_yt_playlist() {
    if ! (( ${+commands[yt-dlp]} )); then
        REPLY="ERROR: yt-dlp is required."
        return 1
    fi

    if (( $# != 2 )); then
        if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
            print -- "$help_page"
            return 0
        else
            REPLY="ERROR: Two args expected. \n\nPass '--help' or '-h' to show help page."
            return 1
        fi
    fi

    local title="$1"
    local url="$2"

    yt-dlp \
        --format "bestaudio[acodec=opus]/bestaudio" \
        --extract-audio \
        --audio-format opus \
        --audio-quality 0 \
        --output "${title}-%(autonumber)02d.%(ext)s" \
        "$url" || {
            REPLY="ERROR: yt-dlp failed"
            return 1
        }

    return 0
}

_dl_yt_playlist "$@" || print -- "$REPLY"
