#!/usr/bin/env zsh

################################################################################
# Download a series of audio files from a youtube playlist in opus format.
# ------------------------------------------------------------------------
# Args:
#     1. File name
#     2. url
#
# Exports:
#     REPLY
################################################################################

emulate -L zsh

setopt pipefail

local help_page
help_page+="Download video in best available quality (audio + video).\n"
help_page+="\n"
help_page+="Args:\n"
help_page+="  1. File name\n"
help_page+="  2. url"

local function _dl_yt_video_max() {
    if ! (( ${+commands[yt-dlp]} )); then
        REPLY="ERROR: yt-dlp is required."
        return 1
    fi

    if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
        print -- "$help_page"
        return 0
    fi

    if (( $# != 2 )); then
        REPLY="ERROR: Two args expected. \n\nPass '--help' or '-h' to show help page."
        return 1
    fi

    local title="$1"
    local url="$2"

    yt-dlp \
        --format-sort "vcodec:av01,vcodec:vp9" \
        --format "bv*+ba/b" \
        --merge-output-format mkv \
        --output "${title}.%(ext)s" \
        "$url" || {
            REPLY="ERROR: yt-dlp failed"
            return 1
        }

    return 0
}

_dl_yt_video_max "$@" || print -- "$REPLY"
