#!/usr/bin/env zsh

################################################################################
# Download a series of audio files from a youtube playlist in opus format, then
# concatenate into a single audio file.
# -------------------------------------
# Args:
#     1. File name
#     2. url
#
# Exports:
#     REPLY
################################################################################

if ! (( ${+commands[yt-dlp]} )); then
    print -- "ERROR: yt-dlp isn't available."
    return 1
fi

emulate -L zsh

setopt pipefail null_glob

local function _dl_and_concat_yt_playlist() {
    if (( $# != 2 )); then
        if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
            local help="Download and concat audio files from yt playlist in .opus format.\n\n"
            help+="Args:\n"
            help+="  1. File name\n"
            help+="  2. url"

            print -- "$help"
            return 0
        else
            REPLY="ERROR: Two args expected. \n\nPass '--help' or '-h' to show help page."
            return 1
        fi
    fi

    local title="$1"
    local url="$2"
    local tmp_dir="./yt_tmp_$$"
    {
        mkdir -p "$tmp_dir" || {
            REPLY="ERROR: mkdir failed"
            return 1
        }

        yt-dlp \
            -f "bestaudio[acodec=opus]/bestaudio" \
            -x \
            --audio-format opus \
            --audio-quality 0 \
            -o "${tmp_dir}/%(playlist_index)05d.%(ext)s" \
            "$url" || {
                REPLY="ERROR: yt-dlp failed"
                return 1
            }

        typeset -a files=( ${tmp_dir}/*.opus )

        # Ensure files exist
        (( ${#files} )) || {
            REPLY="ERROR: No files downloaded"
            return 1
        }

        # Build concat list
        local list_file="${tmp_dir}/files.txt"
        : > "$list_file"

        local file
        for file in "${files[@]}"; do
            printf "file '%s'\n" "${file:t}" >> "$list_file"
        done

        ffmpeg -f concat -safe 0 -i "$list_file" -c copy "${title}.opus" || {
            REPLY="ERROR: ffmpeg failed"
            return 1
        }

    # Ensure cleanup of tmp_dir if dl fails (can't trap function exit)
    } always {
        rm -rf "$tmp_dir"
    }
}

_dl_and_concat_yt_playlist "$@" || print -- "$REPLY"



# Cut from (-ss) / to (-t)
# ffmpeg -i input.opus -ss 00:00:00 -t 00:16:45 -acodec copy output.opus
#
# To cut with frame accuracy use dot notation
# ffmpeg -i input.opus -ss 00:00:00.00 -t 00:16:45.00 -acodec copy output.opus

# Concat two files
# The "filelist" must contain the name of the files
# you want to concatenate formatted like so
#
#--filelist.txt---------
# file 'inputFile1.opus'
# file 'inputFile2.opus'
#-----------------------
#
# ffmpeg -f concat -safe 0 -i filelist.txt -c copy output.opus
