#!/usr/bin/env zsh

################################################################################
# Download video with max audio quality and size-optimized video.
# ---------------------------------------------------------------
# Args:
#     1. File name
#     2. url
#     3. Resolution (optional)
#
# Exports:
#     REPLY
################################################################################

emulate -L zsh

setopt pipefail

local err="\e[31mERROR:\e[m"  # Red hl

local help_page
help_page+="Download video with max audio quality and size-optimized video.\n"
help_page+="\n"
help_page+="Args:\n"
help_page+="  1. File name\n"
help_page+="  2. url\n"
help_page+="  3. (optional) Resolution (e.g. 480, 720, 1080, 1440, 2160)"

local function _dl_yt_video() {
    if ! (( ${+commands[yt-dlp]} )); then
        REPLY="${err} yt-dlp is required."
        return 1
    fi

    # Parse args
    if (( $# != 2 )); then
        if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
            print -- "$help_page"
            return 0
        else
            REPLY="${err} Two args expected. \n\nPass '--help' or '-h' to show help page."
            return 1
        fi
    fi

    local title="$1"
    local url="$2"
    local height="${3:-720}"  # Fallback to 720p is not specified

    if ! [[ "$height" =~ '^[0-9]+$' ]]; then
        REPLY="${err} Resolution must be a number (e.g. 480, 720, 1080, 1440, 2160)"
        return 1
    fi

    yt-dlp \
        --format-sort "res:${height},vcodec:av01,vcodec:vp9,fps:30" \
        --format "bv+ba/b" \
        --merge-output-format mkv \
        --output "${title}.%(ext)s" \
        "$url" || {
            REPLY="${err} yt-dlp failed"
            return 1
        }

    return 0
}

_dl_yt_video "$@" || print -- "$REPLY"
