#!/usr/bin/env zsh

################################################################################
# Download an audio file in opus format from a youtube video.
# -----------------------------------------------------------
# Args:
#     1. File name
#     2. url
#
# Exports:
#     REPLY
################################################################################

emulate -L zsh

setopt pipefail

local function _dl_yt_audio() {
    if ! (( ${+commands[yt-dlp]} )); then
        REPLY="ERROR: yt-dlp isn't available."
        return 1
    fi

    if (( $# != 2 )); then
        if (( $# == 1 )) && [[ "$1" == (--help|-h) ]]; then
            local help="Download audio file from yt video in .opus format.\n\n"
            help+="Args:\n"
            help+="  1. File name\n"
            help+="  2. url"

            print -- "$help"
            return 0
        else
            REPLY="ERROR: Two args expected. \n\nPass '--help' or '-h' to show help page."
            return 1
        fi
    fi

    local title="$1"
    local url="$2"

    yt-dlp \
        -f "bestaudio[acodec=opus]/bestaudio" \
        -x \
        --audio-format opus \
        --audio-quality 0 \
        -o "${title}.%(ext)s" \
        "$url" || {
            REPLY="ERROR: yt-dlp failed"
            return 1
        }
}

_dl_yt_audio "$@" || print -- "$REPLY"
