#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Download a youtube playlist without concatting.                              #
# ---------------------------------------------------------------------------- #
# Args    : URL                                                                #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

command yt-dlp -x --audio-format opus --audio-quality 320K -o "${1}_%(autonumber)02d.%(ext)s" "${2}"
