#!/usr/bin/env zsh

################################################################################
# Download an audio file in opus format from a youtube video.
# -----------------------------------------------------------
# Arguments:
#     1) Desired file name
#     2) URL
# Globals:
#     None
################################################################################

emulate -L zsh

yt-dlp -x --audio-format opus --audio-quality 320K -o "$1.%(ext)s" "$2"
