#!/usr/bin/env zsh

################################################################################
# Download a series of audio files from a youtube playlist in opus format, then
# concatenate into a single audio file.
# -------------------------------------
# Arguments:
#     1) Newly created file name
#     2) URL
# Globals:
#     None
################################################################################

emulate -L zsh

set -e
setopt pipefail null_glob

local function _download_and_concat() {
    if (( $# != 2 )); then
        REPLY="ERROR: Two args expected. \n1. File name \n2. url"
        return 1
    fi

    local output_name="$1"
    local url="$2"
    local tmp_dir="./yt_tmp_$$"

    mkdir -p "$tmp_dir" || return 1

    yt-dlp \
        -x \
        --audio-format opus \
        -o "$tmp_dir/%(playlist_index)05d.%(title)s.%(ext)s" \
        "$url" || return 1

    cd "$tmp_dir" || { REPLY="cd failed"; return 1}

    # Ensure files exist
    local files=( *.opus )
    (( ${#files} )) || { REPLY="No files downloaded"; return 1 }

    # Build concat list
    local list_file="files.txt"
    : > "$list_file"

    for f in $files; do
        printf "file '%s'\n" "$f" >> "$list_file"
    done

    ffmpeg -f concat -safe 0 -i "$list_file" -c copy "../${output_name}.opus"

    cd ..
    rm -rf "$tmp_dir"
}

if ! _download_and_concat "$@"; then
    print "$REPLY"
fi


# Cut from (-ss) / to (-t)
# ffmpeg -i input.opus -ss 00:00:00 -t 00:16:45 -acodec copy output.opus
#
# To cut with frame accuracy use dot notation
# ffmpeg -i input.opus -ss 00:00:00.00 -t 00:16:45.00 -acodec copy output.opus

# Concat two files
# The "filelist" must contain the name of the files
# you want to concatenate formatted like so
#
#--filelist.txt---------
# file 'inputFile1.opus'
# file 'inputFile2.opus'
#-----------------------
#
# ffmpeg -f concat -safe 0 -i filelist.txt -c copy output.opus
