launch --location=vsplit --bias=31 --title " " zsh
launch --location=vsplit --bias=69 --title " " zsh

new_tab
launch --title " " zsh

new_tab
launch --title "󱔘 " zsh
cd ~/.Notes/

new_tab
launch --location=vsplit --title "󰝚 " zsh
cd ~/Desktop/music/
