#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Check all zsh plugins for updates and output diff stat if outdated.          #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

pushd "${DOTFILES}"

git submodule foreach 'git fetch && git diff --stat origin/$(git rev-parse --abbrev-ref HEAD); echo'

popd
