#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Update all zsh plugins.                                                      #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

pushd "${DOTFILES}"

git submodule sync
git submodule update --init --recursive

# git submodule update --remote --merge

popd
