#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Launch broot in single directory view.                                       #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER                                                             #
# ---------------------------------------------------------------------------- #

emulate -L zsh

BUFFER="br --sort-by-type --no-tree"
zle accept-line
