#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# FZF command history and append selected command to the buffer.               #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : BUFFER                                                           #
# Outputs   : Selected command onto the buffer                                 #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# Use `tail -r` in place of `tac`
local selection="$("${XDG_DATA_HOME}"/zsh/history | fzf --no-preview)"

# # Use `tail -r` in place of `tac`
# local selection="$(tail -r ${XDG_DATA_HOME}/zsh/history \
#     | awk '!a[$0]++ && $1 !~ /^:/' \
#     | fzf --no-preview)"

[[ "$selection" ]] && BUFFER="$selection"


# local selection="$(tail -r ${ZDOTDIR}/.zcompcache/.zsh_history \
