#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Fzf command history and append selected command to the buffer.               #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER                                                             #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# The first awk line adds color to the second field (the commmand prefix).
# The second removes the command's index and cleans up white space before
# appending the command to the buffer.
local selection=$( \
    history 0 \
    | awk '{
        $2="\033[38;5;35m"$2"\033[0m";
        print
    }' \
    | fzf \
        --header='Command history.' \
        --no-preview \
    | awk '{
        $1="";
        sub(/^ +/, "");
        print
    }' \
)

if [[ "$selection" ]]; then
    BUFFER="$selection"
    CURSOR=${#BUFFER}
    zle redisplay
fi
