#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Toggle between Rg / Fzf, and open selection in Neovim.                       #
# ---------------------------------------------------------------------------- #
# Args    : Search term                                                        #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# Switch between Ripgrep mode and Fzf filtering mode (ALT-F)
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
fzf --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind 'alt-f:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] &&
        echo "rebind(change)+change-prompt(1. ripgrep  )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
        echo "unbind(change)+change-prompt(2. fzf  )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --prompt '1. ripgrep  ' \
    --delimiter : \
    --header 'alt-f: Toggle between Rg / Fzf.' \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window '+{2}+3/3,~3' \
    --bind 'enter:become(${EDITOR} {1} +{2})'



# # Use bat, if it's available...
# local preview_cmd
# if (( ${+commands[bat]} )); then
#     preview_cmd='bat \
#         --style=numbers \
#         --color=always \
#         --highlight-line=${2} ${1}'
# else
#     # ...otherwise just highlight line with match using sed replace
#     preview_cmd='sed -E "s/(.*'${*}'.*)/'$bg[grey]'\1'$reset_color'/gI;" < ${1}'
# fi

# # Prefer rg over grep
# if (( ${+commands[rg]} )); then
#     command rg \
#         --no-heading \
#         --line-number \
#         --smart-case \
#         --fixed-strings \
#         --color=always "${*}"
# else
#     command grep \
#         --line-number \
#         --recursive \
#         --ignore-case \
#         --color=always \
#         --no-messages "${*}"
# fi | fzf \
#         --delimiter=: \
#         --no-sort \
#         --header='Open Neovim at selected file/line.' \
#         --preview=${preview_cmd} \
#         --bind='enter:become(${EDITOR} {1} +{2})'
