#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Toggle between Rg / Fzf, and open selection in Neovim.                       #
# ---------------------------------------------------------------------------- #
# Args    : Search term                                                        #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# Switch between Ripgrep mode and Fzf filtering mode with <alt-f>
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
fzf --disabled --query "$INITIAL_QUERY" \
    --bind="start:reload:$RG_PREFIX {q}" \
    --bind="change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind='alt-f:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] &&
        echo "rebind(change)+change-prompt(1. ripgrep  )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
        echo "unbind(change)+change-prompt(2. fzf  )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
    --prompt='1. ripgrep  ' \
    --delimiter=: \
    --header='<alt-f> : Toggle between Rg / Fzf.' \
    --preview='bat --color=always {1} --highlight-line {2}' \
    --preview-window='+{2}+3/3,~3' \
    --bind='enter:become(${EDITOR} {1} +{2})'
