#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# FZF z jump list and cd to the selected directory.                            #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER                                                             #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# Note: ls is escaped `\ls` so that the builtin is used in place of my alias
local selection="$(\
    z -l \
    | sed 's/^[0-9. ]*//' \
    | fzf \
        --header='Select a directory to jump to.' \
        --filepath-word \
        --no-sort \
        --query="$*" \
        --preview='\
            LC_COLLATE=C \
            \ls -l -v \
            --almost-all \
            --group-directories-first \
            --classify \
            --color=always \
            --human-readable {}' \
)"

if [[ "$selection" ]]; then
    BUFFER="cd $selection"
    zle accept-line
fi
