#!/usr/bin/env zsh

################################################################################
# List Apple bundle IDs for all currently installed apps.
# -------------------------------------------------------
# Arguments:
#     None
# Globals:
#     None
################################################################################

emulate -L zsh

for app in /Applications/*.app; do
    echo -e "\nApp: $(basename "$app")"
    mdls -name kMDItemCFBundleIdentifier "$app" | grep kMDItemCFBundleIdentifier
done
