#!/usr/bin/env zsh

################################################################################
# Remove all .DS_STORE files in cwd and sub dirs.
# -----------------------------------------------
# Arguments:
#     True / False
# Globals:
#     None
################################################################################

emulate -L zsh

find . -name '.DS_Store' -type f -delete
