#!/usr/bin/env zsh

################################################################################
# Toggle displaying hidden files in the Finder.
################################################################################

emulate -L zsh

local option_state
option_state=$(defaults read com.apple.finder AppleShowAllFiles)

case "$option_state" in
    True)
        defaults write com.apple.finder AppleShowAllFiles False
        print -- "Hiding dotfiles in macOS Finder."
        ;;
    False)
        defaults write com.apple.finder AppleShowAllFiles True
        print -- "Displaying dotfiles in macOS Finder."
        ;;
esac

killall Finder
