#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected file / files with nvim.                        #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --type f \
            --hidden \
            --exclude Library \
            --exclude .git \
            --exclude '*.opus' \
            --exclude '*.mp3' \
            --exclude '*.mp4' \
            --exclude '*.jpeg' \
            --exclude '*.jpg' \
            --exclude '*.png' \
            --exclude '*.webp' \
            --color always \
        | fzf --multi \
    )
else
    selection=$( \
        find . \
            -type f \
            ! -path '*/.git/*' \
        | fzf --multi \
    )
fi

if [[ -z "$selection" ]]; then
    echo -e "\nSearch cancelled."
else
    # Replace line breaks with spaces before passing the
    # output to nvim (enables opening of multiple files)
    nvim $(echo "$selection" | tr '\n' ' ')
fi
