#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected file/s with Neovim.                            #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local FZF_STATE_DIR
(( ${+commands[gdate]} )) \
    && FZF_STATE_DIR="${VI_STATE_DIR}/fzf_state_$(gdate +%Y%m%d%H%M%S%6N)" \
    || FZF_STATE_DIR="${VI_STATE_DIR}/fzf_state_$(date +%Y%m%d%H%M%S)"

mkdir -p "$FZF_STATE_DIR"

local HEADER_TEMPLATE=" Open file/s with Neovim.
Alt _ : Show dotfiles.
Alt ' : Expand dir tree."

local TOGGLE_HIDDEN_FLAG='
    [[ -e "'"$FZF_STATE_DIR"'/hidden" ]] \
        && rm -f "'"$FZF_STATE_DIR"'/hidden" \
        || touch "'"$FZF_STATE_DIR"'/hidden"
'

local TOGGLE_CWD_FLAG='
    [[ -e "'"$FZF_STATE_DIR"'/cwd" ]] \
        && rm -f "'"$FZF_STATE_DIR"'/cwd" \
        || touch "'"$FZF_STATE_DIR"'/cwd"
'

local RELOAD_OPTS='
    local FD_CMD="fd --type=file --max-depth=1 --color=always"
    local HEADER="'"$HEADER_TEMPLATE"'"

    [[ -e "'"$FZF_STATE_DIR"'/hidden" ]] && \
        HEADER="${HEADER/Show dotfiles./Hide dotfiles.}" \
        FD_CMD+=" --hidden"

    [[ -e "'"$FZF_STATE_DIR"'/cwd" ]] && \
        HEADER="${HEADER/Expand dir tree./Collapse dir tree.}" \
        FD_CMD="${FD_CMD/ --max-depth=1}"

    echo "change-header('\$HEADER')+reload('\$FD_CMD')"
'

local selection=$( \
    fd \
        --type=file \
        --max-depth=1 \
        --color=always \
    | fzf \
        --multi \
        --header-border=top \
        --header=$HEADER_TEMPLATE \
        --bind="alt-_:transform:$TOGGLE_HIDDEN_FLAG+$RELOAD_OPTS" \
        --bind="alt-':transform:$TOGGLE_CWD_FLAG+$RELOAD_OPTS" \
)

# Cleanup fzf state directory on exit
[[ -d "$FZF_STATE_DIR" ]] && rm -rf "$FZF_STATE_DIR"

# Open selection with nvim
[[ -n "$selection" ]] && nvim $(echo "$selection" | tr '\n' ' ')



###############################################################

# local HEADER_A=" Open file/s with Neovim. <Tab> : Show dotfiles."
# local HEADER_B=" Open file/s with Neovim. <Tab> : Hide dotfiles."
# local PROMPT_A="Concealing .  "
# local PROMPT_B="Displaying .  "

# local selection=$( \
#     fd \
#         --type=file \
#         --color=always \
#     | fzf \
#         --multi \
#         --header=$HEADER_A \
#         --header-border=top \
#         --prompt=$PROMPT_A \
#         --bind='tab:transform:[[ ! $FZF_PROMPT =~ Concealing ]] \
#             && echo \
#                 "change-prompt('$PROMPT_A')+change-header('$HEADER_A')+reload( \
#                     fd \
#                         --type=file \
#                         --color=always \
#                 )" \
#             || echo \
#                 "change-prompt('$PROMPT_B')+change-header('$HEADER_B')+reload( \
#                     fd \
#                         --type=file \
#                         --hidden \
#                         --color=always \
#                 )"' \
# )

# [[ "$selection" ]] && nvim $(echo "$selection" | tr '\n' ' ')
