#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected file / files with nvim.                        #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

# Use `fd` over `find` if available
if (( ${+commands[fd]} )); then
    selection="$(fd \
    --type f \
    --hidden \
    --exclude Library \
    --exclude .git \
    --exclude '*.opus' \
    --exclude '*.mp3' \
    --exclude '*.mp4' \
    --exclude '*.jpeg' \
    --exclude '*.jpg' \
    --exclude '*.png' \
    --exclude '*.webp' \
    --color always \
    | fzf --multi)"
else
    selection="$(find . -type f ! -path '*/.git/*' | fzf --multi)"
fi

if [[ -z "$selection" ]]; then
    echo -e "\nSearch cancelled."
else
    nvim $(echo "$selection" | tr '\n' ' ')
fi
