#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Render markdown files with Glow.                                             #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : COLUMNS                                                            #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local HEADER_A=" Render markdown. <Tab> : Show dotfiles."
local HEADER_B=" Render markdown. <Tab> : Hide dotfiles."
local PROMPT_A="Concealing .  "
local PROMPT_B="Displaying .  "

local selection=$( \
    fd \
        --type=file \
        --extension=md \
        --color=always \
    | fzf \
        --header=$HEADER_A \
        --prompt=$PROMPT_A \
        --bind='tab:transform:[[ ! $FZF_PROMPT =~ Concealing ]] \
            && echo \
                "change-prompt('$PROMPT_A')+change-header('$HEADER_A')+reload( \
                    fd \
                        --type=file \
                        --extension=md \
                        --color=always \
                )" \
            || echo \
                "change-prompt('$PROMPT_B')+change-header('$HEADER_B')+reload( \
                    fd \
                        --type=file \
                        --hidden \
                        --extension=md \
                        --color=always \
                )"' \
)

if [[ "$selection" ]]; then
    local split_width=$(( COLUMNS - 5 ))
    glow -w "$split_width" "$selection"
fi
