#!/usr/bin/env zsh

################################################################################
# Print the line count for each file in the cwd and its sub directories.
# ----------------------------------------------------------------------
# Arguments:
#     None
# Globals:
#     None
################################################################################

emulate -L zsh

find . -type f -exec wc -l {} +
# fd --type=file --exec wc -l {}
