#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Print the line count for each file in the cwd and it's sub directories.      #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

find . -type f -exec wc -l {} +
# fd --type=file --exec wc -l {}
