#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Render markdown files with Glow.                                             #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection="$(fd --type f --hidden --extension md \
--exclude Library \
--exclude .git \
| fzf --ansi)"

if [[ -z "$selection" ]]; then
    echo -e "\nSearch cancelled."
else
    local term_width="$(tput cols)"
    term_width=$((term_width-10))
    glow -w "$term_width" "$selection"
fi
