#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Move files / directories to the Trash.                                       #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --max-depth 1 \
            --hidden \
            --color always \
        | fzf \
            --header=' Trash selection. <Tab> : Expand tree.' \
            --prompt 'Cwd  ' \
            --multi \
            --bind 'tab:transform:[[ ! $FZF_PROMPT =~ Cwd ]] \
                && echo \
                    "change-prompt(Cwd  )+change-header( Trash selection. <Tab> : Expand tree.)+reload( \
                        fd \
                            --max-depth 1 \
                            --hidden \
                            --color always \
                    )" \
                || echo \
                    "change-prompt(All  )+change-header( Trash selection. <Tab> : Cwd only.)+reload( \
                        fd \
                            --hidden \
                            --color always \
                    )"' \

    )
fi

if [[ "$selection" ]]; then
    local target="$(echo "$selection" | tr '\n' ' ')"
    BUFFER="mv -i ${target}~/.Trash/"
    zle redisplay
fi
