#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Fzf cwd and append `mv` and the rename target (x2) to the command line.      #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER, CURSOR                                                     #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

# Use `eza` over `gls` if available
if (( ${+commands[eza]} )); then
    selection=$( \
        eza \
            --almost-all \
            --icons=always \
            --color=always \
        | fzf \
            --header=' Rename target file / directory.' \
            --header-border=top \
            --no-preview \
    )
elif (( ${+commands[gls]} )); then
    selection=$( \
        gls \
            --almost-all \
            --group-directories-first \
            --color \
        | fzf \
            --header=' Rename target file / directory.' \
            --header-border=top \
            --no-preview \
    )
fi

if [[ "$selection" ]]; then
    # Remove icons if `eza` was used
    (( ${+commands[eza]} )) && selection="$(echo "$selection" | sed -E 's/^.{2}//')"

    BUFFER="mv $selection $selection"

    # Navigate to the start of the second name
    CURSOR=$(( ${#BUFFER} - ${#selection} + 1 ))
    zle vi-cmd-mode
fi
