#!/usr/bin/env zsh

################################################################################
# Print zsh keybindings / help pages.
# -----------------------------------
# Args:     None
# Exports:  ZDOTDIR
################################################################################

emulate -L zsh

local toggle_key='?'

local reload_fzf_opts='
    local fd_cmd="fd --type=file --extension=md --color=always"
    local label=" H:n "
    local content=" Zsh help pages.\n'${toggle_key}' : Show dotfiles."

    if [[ '\$FZF_HEADER_LABEL' == *" H:n "* ]]; then
        fd_cmd+=" --hidden"
        label="${label/ H:n / H:y }"
        content="${content/Show dotfiles./Hide dotfiles.}"
    fi

    printf "%b" \
        "change-header('\${content}')" \
        "+change-header-label('\${label}')" \
        "+reload('\${fd_cmd}')"
'

local selection; selection=$(
    pushd "$ZDOTDIR"

    fd \
        --type=file \
        --extension=md \
        --color=always \
    | fzf \
        --tac \
        --header-border=top \
        --bind="start:transform:${reload_fzf_opts}" \
        --bind="${toggle_key}:transform:${reload_fzf_opts}"

    popd
)

if [[ -n "$selection" ]]; then
    local doc_file="${ZDOTDIR}/${selection}"

    if (( ${+commands[glow]} )); then
        glow "$doc_file"; print "\n"
    elif (( ${+commands[bat]} )); then
        bat --line-range=0:10000 "$doc_file"; print "\n"
    else
        cat "$doc_file"; print "\n"
    fi

    zle redisplay
fi
