#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Fzf zsh history and append selection to the command line.                    #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER, CURSOR                                                     #
# ---------------------------------------------------------------------------- #

emulate -L zsh

# NOTE: The first awk line adds color to the second field (the commmand prefix).
# The second removes the command's index and cleans up white space before
# inserting the command onto the buffer.

local selection=$( \
    history 0 \
    | awk '{
        $2="\033[38;5;35m"$2"\033[0m";
        print
    }' \
    | fzf \
        --header=' Zsh command history.' \
        --no-preview \
    | awk '{
        $1="";
        sub(/^ +/, "");
        print
    }' \
)

if [[ "$selection" ]]; then
    BUFFER="$selection"
    CURSOR=${#BUFFER}
    zle redisplay
fi
