#!/usr/bin/env zsh

################################################################################
# `fzf` zsh history and append selection to the command line.
# -----------------------------------------------------------
# Arguments:
#     None
# Globals:
#     $BUFFER
#     $CURSOR
################################################################################

emulate -L zsh

local selection=$( \
    history 0 \
    | awk '{
        $2="\033[38;5;35m"$2"\033[0m";
        print
    }' \
    | fzf \
        --tac \
        --with-nth=2.. \
        --accept-nth=2.. \
        --no-preview \
        --header-border=top \
        --header=' Zsh command history.' \
)

if [[ -n "$selection" ]]; then
    BUFFER="$selection"
    CURSOR=${#BUFFER}
    zle redisplay
fi
