#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Sudo wrapper which can expand aliases and handle noglob/nocorrect builtins.  #
# ---------------------------------------------------------------------------- #
# Args    : Command                                                            #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

integer glob=1
local -a run
run=(command sudo)

if [[ ${#} -gt 1 && ${1} = -u ]]; then
    run+=(${1} ${2})
    shift; shift
fi

while (( ${#} )); do
    case "${1}" in
        command|exec|-) shift; break ;;
        nocorrect) shift ;;
        noglob) glob=0; shift ;;
        *) break ;;
    esac
done

if (( glob )); then
    ${run} $~==*
else
    ${run} $==*
fi
