#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Print the line count for each file in the cwd and it's sub directories.      #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : None                                                             #
# Outputs   : Line count for all files in cwd and it's sub directories         #
# ---------------------------------------------------------------------------- #

emulate -L zsh

find . -type f -exec wc -l {} +
