#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Add selected files / dirs to the staging area.                               #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals :                                                                    #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection=$( \
    fd --color=always \
    | fzf --multi \
)

if [[ -n "$selection" ]]; then
    local entries=""
    local arrow="\e[0m\e[33m=>\e[m"

    # The (f) flag splits $selection into an array on newlines
    for file in ${(f)selection}; do
        local absolute_file="${file:A}"

        # Only append if the file is not already in $ZSH_STAGE
        if ! grep -Fxq "$absolute_file" "${ZSH_STAGE}"; then
            echo "$absolute_file" >> "${ZSH_STAGE}"
            entries+="  ${arrow} ${file}"$'\n'
        fi
    done
    unset file

    if [[ -n "$entries" ]]; then
        entries=${entries%$'\n'}
        echo "Added to the staging area:"
        echo "$entries"
    fi
fi



##########################################

# if [[ -n "$selection" ]]; then
#     local entries=""
#     local arrow="\e[0m\e[33m=>\e[m"

#     # The (f) flag splits "$selection" into an array on newlines
#     for file in ${(f)selection}; do
#         local absolute_file="${file:A}"

#         # Only append if the file is not already in ZSH_STAGE
#         if ! grep -Fxq "$absolute_file" "${ZSH_STAGE}"; then
#             echo "$absolute_file" >> "${ZSH_STAGE}"
#             entries+="  ${arrow} ${file}"$'\n'
#         fi
#     done
#     unset file

#     if [[ -n "$entries" ]]; then
#         entries=${entries%$'\n'}
#         echo "Added to the staging area:"
#         echo "$entries"
#     fi
# fi




# local HEADER_A="󰐃 Add selection to the stage. <Tab> : Show staging area."
# local HEADER_B="󰐃 Remove selection from the stage. <Tab> : Resume search."
# local PROMPT_A="Concealing .  "
# local PROMPT_B="Displaying .  "

