#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Add selected files / dirs to the staging area.                               #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection=$( \
    fd \
        --absolute-path \
        --color=always \
    | fzf --multi \
)

[[ "${selection}" ]] && echo "${selection}" >> "${ZSH_STAGE}"

# if [[ "${selection}" ]]; then
#     echo "${selection}" >> "${ZSH_STAGE}"
# fi






# local HEADER_A="󰐃 Add selection to the stage. <Tab> : Show staging area."
# local HEADER_B="󰐃 Remove selection from the stage. <Tab> : Resume search."
# local PROMPT_A="Concealing .  "
# local PROMPT_B="Displaying .  "

