#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Download an audio file in opus format from a youtube video.                  #
# ---------------------------------------------------------------------------- #
# Argument 1 : Newly created file name                                         #
# Argument 2 : URL                                                             #
# Globals    : None                                                            #
# Outputs    : Standard yt-dlp output                                          #
# ---------------------------------------------------------------------------- #

emulate -L zsh

yt-dlp -x --audio-format opus --audio-quality 320K -o "$1.%(ext)s" "$2"
