#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Convert all images in cwd to png format.                                     #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

find "$(pwd)" -type f | while IFS= read -r FILE; do
    command ffmpeg -i "$FILE" "${FILE%.*}.png"
done
