#!/usr/bin/env zsh

################################################################################
# `cd` into a child dir of the cwd.
# ---------------------------------
# Args:
#     None
# Exports:
#     BUFFER
#     FZF_KEY
#     FZF_HEADER_LABEL
################################################################################

emulate -L zsh

local hidden_key='?'
local cwd_key='>'

local reload_fzf_opts='
    local fd_cmd="fd --type=directory --color=always"
    local content=" Cd into directory."
    local label=""

    [[ -z '\$FZF_HEADER_LABEL' ]] && label=" H:n E:n " || label='\$FZF_HEADER_LABEL'

    case '\$FZF_KEY' in
        "'"$hidden_key"'")
            [[ '$\label' == *"H:y"* ]] && label="${label/H:y/H:n}" || label="${label/H:n/H:y}"
            ;;
        "'"$cwd_key"'")
            [[ '$\label' == *"E:y"* ]] && label="${label/E:y/E:n}" || label="${label/E:n/E:y}"
            ;;
    esac

    if [[ '\$label' == *"H:n"* ]]; then
        content+="\n'${hidden_key}' : Show dotfiles."
    else
        fd_cmd+=" --hidden"
        content+="\n'${hidden_key}' : Hide dotfiles."
    fi

    if [[ '\$label' == *"E:n"* ]]; then
        fd_cmd+=" --max-depth=1"
        content+="\n'${cwd_key}' : Expand dir tree."
    else
        content+="\n'${cwd_key}' : Collapse dir tree."
    fi

    printf "%b" \
        "change-header('\${content}')" \
        "+change-header-label('\${label}')" \
        "+reload('\${fd_cmd}')"
'

local selection; selection=$(
    fd \
        --type=directory \
        --color=always \
        --max-depth=1 \
    | fzf \
        --tac \
        --header-border=top \
        --bind="${hidden_key}:transform:${reload_fzf_opts}" \
        --bind="${cwd_key}:transform:${reload_fzf_opts}" \
        --bind="start:transform:${reload_fzf_opts}"
)

if [[ -n "$selection" ]]; then
    BUFFER="cd ${selection:q}"
    zle accept-line
fi
