#!/usr/bin/env zsh

################################################################################
# Open file(s) / session with neovim.
# -----------------------------------
# If called:
#   With args)  Open selected files with neovim.
#   No args)    Session.vim exists in cwd, launch Session.vim.
#   No args)    No Session.vim in cwd, launch neovim.
#
# Args:  Files to open / none
################################################################################

emulate -L zsh

if (( $# == 0 )); then
    [[ -e "Session.vim" ]] && nvim -S || nvim
else
    nvim "$@"
fi
