#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, cd to parent dir, and open selected Vim session.                 #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local initial_dir="${0:A:h}"

cd ~

local selection="$( \
    fd Session.vim \
        --format={//} \
        --fixed-strings \
        --extension=.vim \
        --hidden \
        --no-ignore \
        --exclude Library \
        --exclude .git \
        --exclude .cache \
    | fzf \
)"

if [[ -z "$selection" ]]; then
    cd "$initial_dir"
    echo -e "\nSearch cancelled."
else
    cd "$selection"
    command nvim -S
fi
