#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected file/s with Neovim.                            #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection
local HEADER_A=" Open file/s with Neovim. <Tab> : Show dotfiles."
local HEADER_B=" Open file/s with Neovim. <Tab> : Hide dotfiles."
local PROMPT_A="Concealing .  "
local PROMPT_B="Displaying .  "

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --type=file \
            --color=always \
        | fzf \
            --multi \
            --no-preview \
            --header=$HEADER_A \
            --prompt=$PROMPT_A \
            --bind='tab:transform:[[ ! $FZF_PROMPT =~ Concealing ]] \
                && echo \
                    "change-prompt('$PROMPT_A')+change-header('$HEADER_A')+reload( \
                        fd \
                            --type=file \
                            --color=always \
                    )" \
                || echo \
                    "change-prompt('$PROMPT_B')+change-header('$HEADER_B')+reload( \
                        fd \
                            --type=file \
                            --hidden \
                            --color=always \
                    )"' \
    )
else
    selection=$( \
        find . \
            -type f \
            ! -path '*/.git/*' \
        | fzf \
            --multi \
            --header=' Open file/s with Neovim.' \
    )
fi

if [[ "$selection" ]]; then
    # Replace line breaks with spaces before passing the
    # output to nvim (enables opening of multiple files)
    nvim $(echo "$selection" | tr '\n' ' ')
fi
