#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected file / files with Neovim.                      #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --type file \
            --color always \
        | fzf \
            --header=' Open file/s with Neovim. <Tab> : Toggle hidden.' \
            --multi \
            --no-preview \
            --prompt 'Show .  ' \
            --bind 'tab:transform:[[ ! $FZF_PROMPT =~ Show ]] \
                && echo \
                    "change-prompt(Show .  )+reload( \
                        fd \
                            --type file \
                            --color always \
                    )" \
                || echo \
                    "change-prompt(Hide .  )+reload( \
                        fd \
                            --type file \
                            --hidden \
                            --color always \
                    )"' \

    )
else
    selection=$( \
        find . \
            -type f \
            ! -path '*/.git/*' \
        | fzf \
            --header=' Open selected file/s with Neovim.' \
            --multi \
    )
fi

if [[ "$selection" ]]; then
    # Replace line breaks with spaces before passing the
    # output to nvim (enables opening of multiple files)
    nvim $(echo "$selection" | tr '\n' ' ')
fi
