#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Toggle between Rg / Fzf, and open selection in Neovim.                       #
# ---------------------------------------------------------------------------- #
# Args    : Search term                                                        #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

export TEMP=$(mktemp -u)
trap 'rm -f "$TEMP"' EXIT

INITIAL_QUERY="${*:-}"
TRANSFORMER='
    rg_pat={q:1}     # The first word is passed to ripgrep
    fzf_pat={q:2..}  # The rest are passed to fzf

    if ! [[ -r "$TEMP" ]] || [[ $rg_pat != $(cat "$TEMP") ]]; then
        echo "$rg_pat" > "$TEMP"
        printf "reload:sleep 0.1; rg --column --line-number --no-heading --color=always --smart-case %q || true" "$rg_pat"
    fi
    echo "+search:$fzf_pat"
'
fzf --disabled --query "$INITIAL_QUERY" \
    --bind="start,change:transform:$TRANSFORMER" \
    --header=" Open line. Rg searches first word, Fzf everything after." \
    --header-border=top \
    --preview='bat --color=always {1} --highlight-line {2}' \
    --preview-window='right,border-left,<88(up:50%,border-bottom),+{2}+3/3,~3' \
    --delimiter=: \
    --bind='enter:become(nvim {1} +{2})'




############################################################################


# local HEADER_A=" Open line. <Tab> : Switch to Fzf."
# local HEADER_B=" Open line. <Tab> : Switch to Rg."
# local PROMPT_A="Rg  "
# local PROMPT_B="Fzf  "

# # Switch between Ripgrep mode and Fzf filtering mode with <Tab>
# rm -f /tmp/rg-fzf-{r,f}
# RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
# INITIAL_QUERY="${*:-}"
# fzf --disabled --query "$INITIAL_QUERY" \
#     --bind="start:reload:$RG_PREFIX {q}" \
#     --bind="change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
#     --bind='tab:transform:[[ ! $FZF_PROMPT =~ Rg ]] \
#         && echo \
#             "rebind(change)+change-prompt('$PROMPT_A')+change-header('$HEADER_A')+disable-search+transform-query:echo \{q} \
#                 > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" \
#         || echo \
#             "unbind(change)+change-prompt('$PROMPT_B')+change-header('$HEADER_B')+enable-search+transform-query:echo \{q} \
#                 > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
#     --header=$HEADER_A \
#     --header-border=top \
#     --prompt=$PROMPT_A \
#     --delimiter=: \
#     --preview='bat --color=always {1} --highlight-line {2}' \
#     --preview-window='+{2}+3/3,~3' \
#     --bind='enter:become(${EDITOR} {1} +{2})'
