#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Toggle between Rg / Fzf, and open selection in Neovim.                       #
# ---------------------------------------------------------------------------- #
# Args    : Search term                                                        #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

export TEMP=$(mktemp -u)
trap 'rm -f "$TEMP"' EXIT

INITIAL_QUERY="${*:-}"
TRANSFORMER='
    rg_pat={q:1}     # The first word is passed to ripgrep
    fzf_pat={q:2..}  # The rest are passed to fzf

    if ! [[ -r "$TEMP" ]] || [[ $rg_pat != $(cat "$TEMP") ]]; then
        echo "$rg_pat" > "$TEMP"
        printf "reload:sleep 0.1; rg --column --line-number --no-heading --color=always --smart-case %q || true" "$rg_pat"
    fi
    echo "+search:$fzf_pat"
'
fzf --disabled --query "$INITIAL_QUERY" \
    --bind="start,change:transform:$TRANSFORMER" \
    --header-border=top \
    --header=" Open line. Rg searches first word, Fzf everything after." \
    --preview='bat --color=always {1} --highlight-line {2}' \
    --preview-window='right,border-left,<88(up:50%,border-bottom),+{2}+3/3,~3' \
    --delimiter=: \
    --bind='enter:become(nvim {1} +{2})'
