#!/usr/bin/env zsh

################################################################################
# Open file / session with `neovim`.
# If called with args, open selected args (files) with `neovim`.
# If called without args and Session.vim exists in cwd, launch Session.vim.
# If called without args and Session.vim does not exist in cwd, launch `neovim`
# with Neotree open.
# ------------------
# Arguments:
#     Files to open / None
# Globals:
#     None
################################################################################

emulate -L zsh

if [[ "$#" -eq 0 ]]; then
    if [[ -e "Session.vim" ]]; then
        nvim -S
    else
        nvim -c "Neotree reveal"
    fi
else
    nvim "$@"
fi
