#!/usr/bin/env zsh

################################################################################
# Open file / session with `neovim`.
# If called with args, open selected args (files) with `neovim`.
# If called without args and Session.vim exists in cwd, launch Session.vim.
# If called without args and Session.vim does not exist in cwd, launch `neovim`
# with Neotree open.
# ------------------
# Args:  Files to open / none
################################################################################

emulate -L zsh

if (( $# == 0 )); then
    [[ -e "Session.vim" ]] && nvim -S || nvim
else
    nvim "$@"
fi
