#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and open selected Vim session.                                   #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : None                                                             #
# Outputs   : Open target Vim session and cd to parent directory               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local initial_dir="${0:A:h}"

cd ~

local selection="$(fd Session.vim \
--format={//} \
--fixed-strings \
--extension=.vim \
--hidden \
--no-ignore \
--exclude Library \
--exclude .git \
--exclude .cache \
| fzf --ansi)"

if [[ -z "$selection" ]]; then
    cd "$initial_dir"
    echo -e "\nSearch cancelled."
else
    cd "$selection"
    nvim -S
fi
