#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Cd into a child dir of the cwd.                                              #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection
local HEADER_A=" Cd into directory. <Tab> : Expand tree."
local HEADER_B=" Cd into directory. <Tab> : Collapse tree."
local PROMPT_A="Displaying cwd  "
local PROMPT_B="Displaying all  "

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --max-depth=1 \
            --type=directory \
            --hidden \
            --color=always \
        | fzf \
            --header=$HEADER_A \
            --prompt=$PROMPT_A \
            --bind='tab:transform:[[ ! $FZF_PROMPT =~ cwd ]] \
                && echo \
                    "change-prompt('$PROMPT_A')+change-header('$HEADER_A')+reload( \
                        fd \
                            --max-depth=1 \
                            --type=directory \
                            --hidden \
                            --color=always \
                    )" \
                || echo \
                    "change-prompt('$PROMPT_B')+change-header('$HEADER_B')+reload( \
                        fd \
                            --type=directory \
                            --hidden \
                            --color=always \
                    )"' \
    )
fi

if [[ "$selection" ]]; then
    cd "$selection"
    zle accept-line
fi

