#!/usr/bin/env zsh

################################################################################
# Create directories.
# Pass multiple arguments to create multiple directories.
# -------------------------------------------------------
# Args:
#     Directory name(s)
#
# Globals:
#     REPLY
################################################################################

emulate -L zsh

local function _create_new_dir() {
    if (( $# == 0 )); then
        REPLY="ERROR: No argument given."
        return 1
    fi

    local folder="\e[38;5;192m\e[m"
    local arrow="\e[0m\e[33m>\e[m"
    local green="\e[0m\e[33m"
    local color_end="\e[m"

    if (( $# == 1 )); then
        local dir_name="$1"

        mkdir -p -- "$dir_name" || {
            REPLY="ERROR: mkdir failed."
            return 1
        }

        cd "$dir_name" || {
            REPLY="ERROR: cd failed."
            return 1
        }

        local msg
        msg+="${arrow}  ${folder} ${dir_name}"
        msg+="\n${green}Created${color_end}."
        msg+="\ncwd changed to: ${folder} ${dir_name}"

        print -- "$msg"
    else
        typeset -a created_dirs

        for dir in "$@"; do
            if mkdir -p -- "$dir"; then
                created_dirs+=( "$dir" )
            else
                REPLY="ERROR: mkdir failed."
                return 1
            fi
        done

        # If at least one dir was successfully created
        if (( ${#created_dirs[@]} > 0 )); then
            local dir msg
            for dir in "${created_dirs[@]}"; do
                msg+="${arrow}  ${folder} ${dir}\n"
            done
            msg+="\n${green}Created${color_end}."

            print -- "$msg"
        fi
    fi

    return 0
}

_create_new_dir "$@" || print -- "$REPLY"
