#!/usr/bin/env zsh

################################################################################
# Create directory.
# Pass multiple arguments to create multiple directories.
# -------------------------------------------------------
# Args:     Directory name(s)
# Exports:  REPLY
################################################################################

emulate -L zsh

local function _create_new_dir() {
    local err="\e[31mERROR:\e[m"        # Red hl
    local created="\e[32mCreated:\e[m"  # Green hl

    if (( $# == 0 )); then
        REPLY="${err} No argument given."
        return 1
    fi

    if (( $# == 1 )); then
        local dir="$1"

        [[ -e "$dir" ]]    && { REPLY="${err} './${dir}' already exists."; return 1 }
        mkdir -p -- "$dir" || { REPLY="${err} mkdir './${dir}' failed.";   return 1 }
        cd "$dir"          || { REPLY="${err} cd failed.";                 return 1 }

        local output_msg
        output_msg+="${created} '${PWD}'\n"
        output_msg+="Changed cwd to './${dir}'"

        print -- "$output_msg"
    else
        typeset -a created_dirs

        local dir error_msg
        for dir in "$@"; do
            if [[ -e "$dir" ]]; then
                error_msg+="${err} './${dir}' already exists.\n"
            else
                if mkdir -p -- "$dir"; then
                    created_dirs+=( "$dir" )
                else
                    error_msg+="${err} mkdir './${dir}' failed.\n"
                fi
            fi
        done
        error_msg=${error_msg%\\n}

        # Print error messages if any
        [[ -n "$error_msg" ]] && print -- "$error_msg"

        # If at least one dir was successfully created
        if (( ${#created_dirs[@]} > 0 )); then
            local new_dir output_msg
            for new_dir in "${created_dirs[@]}"; do
                output_msg+="${created} '${PWD}/${new_dir}'\n"
            done
            output_msg=${output_msg%\\n}

            print -- "$output_msg"
        fi
    fi

    return 0
}

_create_new_dir "$@" || print -- "$REPLY"
