#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search for, and cd to the selected directory.                                #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection

if (( ${+commands[fd]} )); then
    selection=$( \
        fd \
            --type d \
            --hidden \
            --exclude Library \
            --exclude .git \
            --color always \
        | fzf \
    )
else
    selection=$( \
        find . \
            -type d \( \
            -path "./Library/*" -or \
            -path "./.git/*" -or \
            -path "./node_modules/*" \) \
            -prune -o -type d -print \
        | fzf \
    )
fi

if [[ "$selection" ]]; then
    cd "$selection"
fi
