#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Cd up a given number of directories in the tree.                             #
# If no args are passed, cd up one directory.                                  #
# ---------------------------------------------------------------------------- #
# Args    : Number of directories to traverse upwards in the tree / None       #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

if [[ "$#" < 1 ]]; then
    cd ..
else
    local rpt=$(printf "%${1}s")
    local cdstr=${rpt// /..\/}
    cd $cdstr
fi
