#!/usr/bin/env zsh

################################################################################
# Pipe `z` jump into `fzf` and `cd` to the selected directory.
# ------------------------------------------------------------
# Arguments:
#     None
# Globals:
#     $BUFFER
################################################################################

emulate -L zsh

# NOTE: When using delimiters in awk if you define your input file separator
# to be ',' and you want to keep it, then you have to define your output file
# separator as ',' also.
#
# https://unix.stackexchange.com/questions/427421/awk-unintentionally-removing-commas

local selection=$( \
    z -l \
    | sed 's/^[0-9. ]*//' \
    | awk -F "/" '{
        OFS="/";
        $NF="\033[38;5;69m"$NF"\033[0m";
        print
    }' \
    | fzf \
        --header='󱃅 Teleport to selected directory.' \
        --header-border=top \
        --filepath-word \
        --no-sort \
        --tac \
)

if [[ -n "$selection" ]]; then
    BUFFER="cd ${selection:q}"
    zle accept-line
fi
