#!/usr/bin/env zsh

################################################################################
# Pipe `z` jump into `fzf` and `cd` to the selected directory.
# ------------------------------------------------------------
# Args:
#     None
#
# Exports:
#     BUFFER
################################################################################

emulate -L zsh

local selection
selection=$(
    typeset -a lines=( "${(@f)$(z -l)}" )

    local line
    for line in "${lines[@]}"; do
        sep="/"
        path="/${line#*/}"
        dir="${path:h}"
        base="${path:t}"
        [[ $dir == "/" ]] && sep=""
        printf '%b\n' "${dir}${sep}\033[38;5;69m${base}\033[0m"
    done | fzf \
        --header='󱃅 Teleport to selected directory.' \
        --header-border=top \
        --filepath-word \
        --no-sort \
        --tac
)

if [[ -n $selection ]]; then
    BUFFER="cd ${selection:q}"
    zle accept-line
fi
