#!/usr/bin/env zsh

################################################################################
# `git` add, commit, push.
# ------------------------
# Arguments:
#     Commit message
# Globals:
#     None
################################################################################

emulate -L zsh

git add .

if [[ -n "$1" ]]; then
    git commit -m "$1"
else
    git commit -m update
fi

git push -u origin main
