#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Git log browser with Fzf.                                                    #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : None                                                               #
# ---------------------------------------------------------------------------- #

emulate -L zsh

git rev-parse --is-inside-work-tree &> /dev/null || return

git log \
    --date=short \
    --format="%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)" \
    --graph \
    --color=always \
| fzf \
    --header='Press CTRL-S to toggle sort' \
    --no-sort \
    --multi \
    --bind='ctrl-s:toggle-sort' \
    --preview='grep -o "[a-f0-9]\{7,\}" <<< {} \
        | xargs git show --color=always \
        | head -200' \
| grep -o "[a-f0-9]\{7,\}"
