#!/usr/bin/env zsh

################################################################################
# Initialize a new `git` repo in the cwd.
# ---------------------------------------
# Arguments:
#     URL of the target git repo
# Globals:
#     None
################################################################################

emulate -L zsh

local url="$1"

if [[ -z "$url" ]]; then
    echo -e "\nNo URL provided."
else
    git init
    git add -A
    git commit -m "first commit"
    git branch -M main
    git remote add origin "$url"
    git push -u origin main
fi
