#!/usr/bin/env zsh

# Move files to the Trash when using rm.
#------------------------------------------------------------------------------#
emulate -L zsh

local ZSH_TRASH=${HOME}/.Trash
local trashcan="\e[38;5;117m\e[m"
local arrow="\e[0m\e[33m>\e[m"
local message
local arg

if [[ "$#" -eq 0 ]]; then
    echo -e "\nNo argument given."
    return 1
fi

echo " "
for arg in "${@}"; do
    if [[ ${arg} == -* ]]; then continue; fi

    if [[ -L ${arg} ]]; then
        message="Remove softlink ${arg}."
        rm "${arg}"
    else
        message="${arg}"
        local file_name=$(basename "${arg}")
        local file_name_no_ext="${file_name%.*}"
        local extension="${file_name##*.}"

        if [[ -d "${arg}" ]]; then
            new_name="${file_name}_$(date '+%Y%m%d%H%M%S')"
        else
            new_name="${file_name_no_ext}_$(date '+%Y%m%d%H%M%S').${extension}"
        fi

        mv "${arg}" "${ZSH_TRASH}/${new_name}"

        if [[ "${?}" == 0 ]]; then
            echo -e "${trashcan}  ${message}"
        else
            return 1
        fi
    fi
done
