#!/usr/bin/env zsh

emulate -L zsh

local initial_dir="${0:A:h}"
cd "${ZSCRIPTDIR}"

# Search cheat sheet ignoring files with a leading underscore
# Use `fd` over `find` if available
if (( ${+commands[fd]} )); then
    local selection="$(fd --type f --exclude '_*' | fzf)"
elif (( ${+commands[find]} )); then
    local selection="$(find . -type f ! -name '_*' | fzf)"
fi

cd "$initial_dir"

if [[ "$selection" ]]; then
    # Strip everything up to, and including the slash
    BUFFER="${selection#*/}"
    CURSOR=${#BUFFER}
fi
