#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Terminal cheat sheet powered by fzf.                                         #
# ---------------------------------------------------------------------------- #
# Args    : None                                                               #
# Globals : BUFFER, CURSOR, ZSCRIPTDIR                                         #
# ---------------------------------------------------------------------------- #

emulate -L zsh

pushd "$ZSCRIPTDIR"

# Search cheat sheet, ignoring files with a leading underscore
local selection=$( \
    fd \
        --type=file \
        --exclude='_*' \
        --color=always \
    | awk -F "_" '{
        OFS="_";
        if ($NF == "x") {
            $NF="\033[38;5;191m"$NF"\033[0m";
        }
        print
    }' \
    | fzf \
        --header=' Zsh cheat sheet. Green x : Immediate execution.' \
        --header-border=top \
)

popd

if [[ "$selection" ]]; then
    # Strip everything up to, and including the slash
    BUFFER="${selection#*/}"

    # Execute marked commands on selection
    if [[ "${BUFFER: -2}" == "_x" ]]; then
        zle accept-line
    else
        # Move the cursor to the end of the appended command
        CURSOR=${#BUFFER}
        zle redisplay
    fi
fi
