#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search and cd to the selected directory.                                     #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : None                                                             #
# Outputs   : None                                                             #
# ---------------------------------------------------------------------------- #

emulate -L zsh

local selection
if (( ${+commands[fd]} )); then
    selection="$(fd --color=always --type=directory --hidden\
    --exclude Library\
    --exclude .git\
    | fzf --ansi)"
else
    selection="$(find . -type d \(\
    -path "./Library/*" -or\
    -path "./.git/*" -or\
    -path "./node_modules/*" \)\
    -prune -o -type d -print\
    | fzf --ansi)"
fi

if [[ -z "$selection" ]]; then
    echo -e "\nSearch cancelled."
else
    cd "$selection"
fi
