#!/usr/bin/env zsh

# Search and cd to the selected directory.
#------------------------------------------------------------------------------#
emulate -L zsh

local selection

if (( ${+commands[fd]} )); then
    selection="$(fd --color=always --type=directory --hidden \
    --exclude Library \
    --exclude .git \
    --exclude .npm \
    --exclude .vscode \
    | fzf --ansi)"
else
    # Use find if fd is not available
    selection="$(find . -type d \( \
        -name Library -o \
        -name .git -o \
        -name .npm -o \
        -name .vscode \
    \) -prune -o -type d -print 2>/dev/null | fzf --ansi)"
fi

if [[ -z "$selection" ]]; then
    echo -e "\nSearch cancelled."
else
    cd "$selection"
    echo ''; lsd -A -v
fi



# local selection="$(fd --color=always --type=directory --hidden \
# --exclude Library \
# --exclude .git \
# --exclude .npm \
# --exclude .vscode \
# | fzf --ansi)"

# if [[ -z "$selection" ]]; then
#     echo -e "\nSearch cancelled."
# else
#     cd "$selection"
#     echo ''; lsd -A -v
# fi
