#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Jump up any number of directories in the tree.                               #
# ---------------------------------------------------------------------------- #
# Arguments : Number of directories to traverse upwards in the tree / None     #
# Globals   : None                                                             #
# Outputs   : Change cwd to target directory                                   #
# ---------------------------------------------------------------------------- #

emulate -L zsh

if [[ "$#" < 1 ]]; then
    cd ..
else
    local rpt=$(printf "%${1}s")
    local cdstr=${rpt// /..\/}
    cd $cdstr
fi
