#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Open file / session with nvim.                                               #
# ---------------------------------------------------------------------------- #
# Arguments : Files to open / None                                             #
# Globals   : None                                                             #
# Outputs   : Opens target files / session with nvim                           #
# ---------------------------------------------------------------------------- #

# If called without args and Session.vim exists in cwd, launch Session.vim.
# If called without args and Session.vim does not exist in cwd, launch nvim
# with Neotree open.
# If called with args, open selected args (files) with nvim.

emulate -L zsh

if [[ "$#" -eq 0 ]]; then
    if [[ -e "Session.vim" ]]; then
        nvim -S
    else
        nvim -c "Neotree reveal"
    fi
else
    nvim "$@"
fi
