#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Search term in cwd, pipe it into fzf, and open selection in nvim.            #
# ---------------------------------------------------------------------------- #
# Arguments : Search term                                                      #
# Globals   : None                                                             #
# Outputs   : Pipe rg results into fzf and pass selection to nvim              #
# ---------------------------------------------------------------------------- #

emulate -L zsh

rg --smart-case --line-number "${*:-}" |
    fzf \
        --delimiter : \
        --preview 'bat {1} --highlight-line {2}' \
        --bind 'enter:become(nvim {1} +{2})'
