#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Convert all images in cwd to png format.                                     #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : None                                                             #
# Outputs   : Newly formatted images in the cwd                                #
# ---------------------------------------------------------------------------- #

emulate -L zsh

find "$(pwd)" -type f | while IFS= read -r FILE; do
    ffmpeg -i "$FILE" "${FILE%.*}.png"
done
