#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Create a specified number of files.                                          #
# ---------------------------------------------------------------------------- #
# Arguments : Integer (number of files to create)                              #
# Globals   : None                                                             #
# Outputs   : Specified number of new files in cwd                             #
# ---------------------------------------------------------------------------- #

emulate -L zsh

if [[ "$#" -eq 1 ]] && [[ "$1" =~ ^[0-9]+$ ]]; then
    for ((i=1; i<=$1; i++)); do
        touch "$(printf "%02d_file.txt" "$i")"
    done
else
    echo -e "\nError: Argument must be a positive integer."
    return 1
fi
