#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Print all ansi color codes.                                                  #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : None                                                             #
# Outputs   : A highlighted list of all 255 ansi color codes                   #
# ---------------------------------------------------------------------------- #

emulate -L zsh

for code in {0..255}; do
    echo -e "\e[38;5;${code}m"'\\e[38;5;'"$code"m"\e[0m"
done
