#!/usr/bin/env zsh

################################################################################
# List Apple bundle IDs for all currently installed apps.
# -------------------------------------------------------
# Args:  None
################################################################################

emulate -L zsh

for app in /Applications/*.app; do
    print -- "\nApp: $(basename "$app")"
    mdls -name kMDItemCFBundleIdentifier "$app" | grep kMDItemCFBundleIdentifier
done
