#!/usr/bin/env zsh

# ---------------------------------------------------------------------------- #
# Launch broot in single directory view.                                       #
# ---------------------------------------------------------------------------- #
# Arguments : None                                                             #
# Globals   : BUFFER                                                           #
# Outputs   : Launch broot with tree view disabled by default                  #
# ---------------------------------------------------------------------------- #

emulate -L zsh

BUFFER="br --sort-by-type --no-tree"
zle accept-line
