#!/usr/bin/env zsh

################################################################################
# Create files.
# Pass multiple arguments to create multiple files.
# -------------------------------------------------
# Args:     File name(s)
# Exports:  REPLY
################################################################################

emulate -L zsh

local function _create_new_file() {
    local err="\e[31mERROR:\e[m"        # Red hl
    local created="\e[32mCreated:\e[m"  # Green hl

    if (( $# == 0 )); then
        REPLY="${err} No argument given."
        return 1
    fi

    typeset -a created_files

    local file error_msg
    for file in "$@"; do
        if [[ -e "$file" ]]; then
            error_msg+="${err} '${file}' already exists.\n"
        else
            if touch "$file"; then
                created_files+=( "$file" )
            else
                error_msg+="${err} touch '${file}' failed.\n"
            fi
        fi
    done
    error_msg=${error_msg%\\n}

    # Print error messages if any
    [[ -n "$error_msg" ]] && print -- "$error_msg"

    # If at least one file was successfully created
    if (( ${#created_files[@]} > 0 )); then
        local new_file output_msg
        for new_file in "${created_files[@]}"; do
            output_msg+="${created} '${new_file}'\n"
        done
        output_msg=${output_msg%\\n}

        print -- "$output_msg"
    fi

    return 0
}

_create_new_file "$@" || print -- "$REPLY"
